logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-center

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:4000/uaa/user
      prefer-token-info: false
#    client:
#      access-token-uri: http://localhost:4000/uaa/oauth/token
#      user-authorization-uri: http://localhost:4000/uaa/oauth/authorize
#      client-id: webapp
#      client-secret: webapp


