logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
#            timeoutInMilliseconds: 10000
            timeoutInMilliseconds: 80000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-center

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:4000/uaa/user
      prefer-token-info: false


