logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-center:8761/eureka/

spring:
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-center

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/auth-service/user
    client:
      access-token-uri: http://localhost:5000/auth-service/oauth/token
      user-authorization-uri: http://localhost:5000/auth-service/oauth/authorize
      client-id: webApp
      client-secret: webApp

