logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-center:8761/eureka/

spring:
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-center

