spring:
  jpa:
    show-sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

security:
    oauth2:
      resource:
        filter-order: 3